# Generated by Django 5.1.6 on 2025-02-27 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vtp', '0002_local'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Local',
        ),
    ]
