# Generated by Django 5.1.6 on 2025-03-07 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vtp', '0003_delete_local'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datatype',
            old_name='datatype',
            new_name='network',
        ),
        migrations.AlterField(
            model_name='datatype',
            name='name',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='network',
            name='name',
            field=models.CharField(max_length=15),
        ),
        migrations.CreateModel(
            name='Passmode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('datatype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vtp.datatype')),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vtp.network')),
            ],
        ),
        migrations.DeleteModel(
            name='ReqData',
        ),
    ]
