# Generated by Django 5.1.6 on 2025-03-11 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vtp', '0004_rename_datatype_datatype_network_alter_datatype_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datatype',
            name='name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='network',
            name='name',
            field=models.CharField(max_length=40),
        ),
        migrations.CreateModel(
            name='Permode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=124)),
                ('datatype', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vtp.datatype')),
                ('network', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vtp.network')),
            ],
        ),
        migrations.DeleteModel(
            name='Passmode',
        ),
    ]
