# Generated by Django 5.1.6 on 2025-03-12 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vtp', '0005_alter_datatype_name_alter_network_name_permode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dataplan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('datatype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vtp.datatype')),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vtp.network')),
            ],
        ),
        migrations.AddField(
            model_name='permode',
            name='dataplan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vtp.dataplan'),
        ),
    ]
