# Generated by Django 5.1.6 on 2025-03-13 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vtp', '0006_dataplan_permode_dataplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airtime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airtime', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='AirtimeTran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=124)),
                ('amount', models.CharField(max_length=124)),
                ('airtime', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vtp.network')),
            ],
        ),
    ]
