# Generated by Django 5.1.4 on 2025-03-14 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vtp', '0007_airtime_airtimetran'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airtimetran',
            name='airtime',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vtp.airtime'),
        ),
    ]
